### ISSUE TITLE
Updating the database using dumpRequirements.sh fails

### ISSUE THREAD

**Issue by dorazouri** [SecurityRAT/SecurityRAT-dockercompose#2]
Running the sql dump command from the #7 step in the README file, fails with the following error:
`sh: 1: ./var/dumpRequirements.sh: not found`

Fixed by opening a shell to the container and running:
`root@0587bc2692e2:/var# /bin/bash dumpRequirements.sh`

Therefore, in order to mitigate this error, the command in README can be replaced to:
`docker exec securityrat-mysql sh -c '/bin/bash /var/dumpRequirements.sh'`
(explicit path for the sh script + explicit use of /bin/bash instead of sh interpreter)

**Comment by rylyade1** [comment]
Fix merged. I am closing this issue.
